version: 2.1

step-library:
  - &restore-cache
      restore_cache:
        keys:
          - cache-mbgeocoder-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
          - cache-mbgeocoder-v1-{{ .Environment.CIRCLE_JOB }} # used if checksum fails

  - &save-cache
      save_cache:
        key: cache-mbgeocoder-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
        paths:
          - Carthage

  - &prepare
      run:
        name: Prepare
        command: |
          curl -L https://github.com/Carthage/Carthage/releases/download/0.38.0/Carthage.pkg >> Carthage.pkg
          sudo installer -pkg Carthage.pkg -target /
          echo "foo" > ~/.mapbox

  - &publish-codecov
      run:
        name: Publish code coverage
        command: bash <(curl -s https://codecov.io/bash)

jobs:
  SPM-job:
    parameters:
      xcode:
        type: string
    macos:
      xcode: << parameters.xcode >>
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: swift build
      - run: swift test

  build-job:
    parameters:
      xcode:
        type: string
      device:
        type: string
        default: "iPhone 8 Plus"
      iOS:
        type: string
        default: "12.1"
      watchOS:
        type: string
        default: "5.0"
      tvOS:
        type: string
        default: "12.0"
      test:
        type: boolean
        default: true
      codecoverage:
        type: boolean
        default: false
    macos:
      xcode: << parameters.xcode >>
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - run:
          name: Install prerequisites
          command: |
            if [ $(xcversion simulators | grep -cF "iOS << parameters.iOS >> Simulator (installed)") -eq 0 ]; then xcversion simulators --install="iOS << parameters.iOS >>" || true; fi
      - *restore-cache
      - run:
          name: Dependencies
          command: |
            carthage bootstrap --platform ios --cache-builds --configuration Debug --no-use-binaries --use-xcframeworks
            carthage bootstrap --platform tvos --cache-builds --configuration Debug --no-use-binaries --use-xcframeworks
            carthage bootstrap --platform macos --cache-builds --configuration Debug --no-use-binaries --use-xcframeworks
            carthage bootstrap --platform watchos --cache-builds --configuration Debug --no-use-binaries --use-xcframeworks
      - *save-cache
      - run:
          name: iOS
          command: xcodebuild -sdk iphonesimulator -project MapboxGeocoder.xcodeproj -scheme 'MapboxGeocoder iOS' -destination 'platform=iOS Simulator,OS=<< parameters.iOS >>,name=<< parameters.device >>' clean build <<# parameters.test >>test<</ parameters.test >><<# parameters.codecoverage >> -enableCodeCoverage "YES"<</ parameters.codecoverage >>
      - when:
          condition: << parameters.codecoverage >>
          steps:
            - *publish-codecov
      - run:
          name: tvOS
          command: xcodebuild -project MapboxGeocoder.xcodeproj -scheme 'MapboxGeocoder tvOS' -destination 'platform=tvOS Simulator,name=Apple TV 4K (at 1080p),OS=<< parameters.tvOS >>' clean build <<# parameters.test >>test <</ parameters.test >> <<# parameters.codecoverage >>-enableCodeCoverage YES<</ parameters.codecoverage >>
      - when:
          condition: << parameters.codecoverage >>
          steps:
            - *publish-codecov
      - run:
          name: macOS
          command: xcodebuild -project MapboxGeocoder.xcodeproj -scheme 'MapboxGeocoder Mac' clean build<<# parameters.test >> test <</ parameters.test >><<# parameters.codecoverage >>-enableCodeCoverage YES<</ parameters.codecoverage >>
      - run:
          name: watchOS
          command: xcodebuild -project MapboxGeocoder.xcodeproj -scheme 'MapboxGeocoder watchOS' -destination 'platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm,OS=<< parameters.watchOS >>' clean build

workflows:
  workflow:
    jobs:
      - build-job:
          name: "Xcode_12.5.1"
          xcode: "12.5.1"
          iOS: "14.5"
          tvOS: "14.0"
          watchOS: "7.0"
          codecoverage: false
      - SPM-job:
          name: "SPM"
          xcode: "12.5.1"
